CREATE TABLE "limecab_account" (
	"userId" varchar(255) NOT NULL,
	"type" varchar(255) NOT NULL,
	"provider" varchar(255) NOT NULL,
	"providerAccountId" varchar(255) NOT NULL,
	"refresh_token" text,
	"access_token" text,
	"expires_at" integer,
	"token_type" varchar(255),
	"scope" varchar(255),
	"id_token" text,
	"session_state" varchar(255),
	CONSTRAINT "limecab_account_provider_providerAccountId_pk" PRIMARY KEY("provider","providerAccountId")
);
--> statement-breakpoint
CREATE TABLE "limecab_driver" (
	"id" varchar(255) PRIMARY KEY NOT NULL,
	"userId" varchar(255) NOT NULL,
	"name" varchar(128) NOT NULL,
	"ratingHundredths" integer DEFAULT 500 NOT NULL,
	"vehicleMake" varchar(64) NOT NULL,
	"vehicleModel" varchar(64) NOT NULL,
	"vehicleColor" varchar(32) NOT NULL,
	"vehiclePlate" varchar(16) NOT NULL,
	"available" boolean DEFAULT false NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	CONSTRAINT "limecab_driver_user_id_unique" UNIQUE("userId")
);
--> statement-breakpoint
CREATE TABLE "limecab_post" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "limecab_post_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256),
	"createdById" varchar(255) NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "limecab_session" (
	"sessionToken" varchar(255) PRIMARY KEY NOT NULL,
	"userId" varchar(255) NOT NULL,
	"expires" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "limecab_trip" (
	"id" varchar(255) PRIMARY KEY NOT NULL,
	"userId" varchar(255) NOT NULL,
	"status" varchar(16) DEFAULT 'requested' NOT NULL,
	"pickupAddress" varchar(512) NOT NULL,
	"pickupLatitude" double precision,
	"pickupLongitude" double precision,
	"pickupMeetingPoint" varchar(256),
	"destinationAddress" varchar(512) NOT NULL,
	"destinationLatitude" double precision,
	"destinationLongitude" double precision,
	"productId" varchar(64) NOT NULL,
	"baseCents" integer NOT NULL,
	"distanceCents" integer NOT NULL,
	"timeCents" integer NOT NULL,
	"bookingCents" integer NOT NULL,
	"totalCents" integer NOT NULL,
	"distanceMiles" double precision NOT NULL,
	"tripMinutes" integer NOT NULL,
	"arrivalMinutes" integer NOT NULL,
	"pickupPin" varchar(8) NOT NULL,
	"driverId" varchar(255),
	"requestIdempotencyKey" varchar(255),
	"requestedAt" timestamp with time zone NOT NULL,
	"cancelledAt" timestamp with time zone,
	"completedAt" timestamp with time zone,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone,
	CONSTRAINT "limecab_trip_request_idempotency_unique" UNIQUE("requestIdempotencyKey")
);
--> statement-breakpoint
CREATE TABLE "limecab_user" (
	"id" varchar(255) PRIMARY KEY NOT NULL,
	"name" varchar(255),
	"email" varchar(255) NOT NULL,
	"emailVerified" timestamp with time zone,
	"image" varchar(255)
);
--> statement-breakpoint
CREATE TABLE "limecab_verification_token" (
	"identifier" varchar(255) NOT NULL,
	"token" varchar(255) NOT NULL,
	"expires" timestamp with time zone NOT NULL,
	CONSTRAINT "limecab_verification_token_identifier_token_pk" PRIMARY KEY("identifier","token")
);
--> statement-breakpoint
ALTER TABLE "limecab_account" ADD CONSTRAINT "limecab_account_userId_limecab_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."limecab_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "limecab_driver" ADD CONSTRAINT "limecab_driver_userId_limecab_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."limecab_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "limecab_post" ADD CONSTRAINT "limecab_post_createdById_limecab_user_id_fk" FOREIGN KEY ("createdById") REFERENCES "public"."limecab_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "limecab_session" ADD CONSTRAINT "limecab_session_userId_limecab_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."limecab_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "limecab_trip" ADD CONSTRAINT "limecab_trip_userId_limecab_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."limecab_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "limecab_trip" ADD CONSTRAINT "limecab_trip_driverId_limecab_driver_id_fk" FOREIGN KEY ("driverId") REFERENCES "public"."limecab_driver"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "limecab_account_user_id_idx" ON "limecab_account" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "limecab_driver_available_idx" ON "limecab_driver" USING btree ("available");--> statement-breakpoint
CREATE INDEX "limecab_created_by_idx" ON "limecab_post" USING btree ("createdById");--> statement-breakpoint
CREATE INDEX "limecab_name_idx" ON "limecab_post" USING btree ("name");--> statement-breakpoint
CREATE INDEX "limecab_t_user_id_idx" ON "limecab_session" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "limecab_trip_user_id_idx" ON "limecab_trip" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "limecab_trip_status_idx" ON "limecab_trip" USING btree ("status");--> statement-breakpoint
CREATE INDEX "limecab_trip_requested_at_idx" ON "limecab_trip" USING btree ("requestedAt");